name: Package Google Chrome as IntuneWin

on:
  workflow_dispatch:

jobs:
  build-intunewin:
    runs-on: windows-latest

    steps:
      - name: Create directories
        run: |
          New-Item -Path input -ItemType Directory
          New-Item -Path output -ItemType Directory

      - name: Download Google Chrome Offline Installer (Enterprise)
        run: |
          Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/375.126/chrome_installer.exe" -OutFile "input\ChromeSetup.exe"

      - name: Download Microsoft Win32 Content Prep Tool v1.8.6
        run: |
          Invoke-WebRequest -Uri "https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/releases/download/v1.8.6/IntuneWinAppUtil.exe" -OutFile "IntuneWinAppUtil.exe"

      - name: Package using IntuneWinAppUtil
        run: |
          .\IntuneWinAppUtil.exe -c ".\input" -s "ChromeSetup.exe" -o ".\output" -q

      - name: Upload .intunewin package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-intunewin
          path: output/*.intunewin
