name: AutoPkg Build macOS PKG

on:
  workflow_dispatch:

jobs:
  autopkg:
    runs-on: macos-latest

    steps:
      - name: Install AutoPkg with pipx
        run: |
          echo "Installing AutoPkg via pipx"
          pipx install autopkg

      - name: Add AutoPkg recipe repo (community recipes)
        run: |
          pipx run autopkg repo-add https://github.com/autopkg/recipes.git

      - name: Run AutoPkg recipe for Visual Studio Code
        run: |
          pipx run autopkg run visual-studio-code.pkg --verbose

      - name: Find generated PKG installer path
        run: |
          PKG_PATH=$(find ~/Library/AutoPkg/Cache/local.pkg/VisualStudioCode/ -name "*.pkg" | head -n 1)
          echo "PKG_PATH=$PKG_PATH" >> $GITHUB_ENV
          if [ -z "$PKG_PATH" ]; then
            echo "Error: PKG file not found in AutoPkg cache!"
            exit 1
          fi
          echo "Found PKG installer at $PKG_PATH"

      - name: Upload PKG installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-macos-pkg
          path: ${{ env.PKG_PATH }}
