name: Build Visual Studio Code Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show current working directory and recipes folder for debug
        run: |
          echo "Current working directory:"
          pwd
          echo "Repository root contents:"
          ls -la
          echo "Recipes folder contents:"
          ls -la ./recipes

      - name: Clean AutoPkg cached recipe repositories
        run: |
          echo "Removing old AutoPkg recipe caches..."
          rm -rf ~/Library/AutoPkg/RecipeRepos/*
          echo "Cache cleanup done."

      - name: Download and install AutoPkg
        run: |
          echo "Downloading AutoPkg installer..."
          curl -L -o autopkg.pkg https://github.com/autopkg/autopkg/releases/download/v2.7.5/AutoPkg-2.7.5.pkg

          if [ ! -f autopkg.pkg ]; then
            echo "Error: AutoPkg installer package missing!"
            exit 1
          fi

          filesize=$(stat -f%z autopkg.pkg)
          echo "Installer package size: $filesize bytes"

          if [ "$filesize" -lt 100000 ]; then
            echo "Error: Installer package is suspiciously small; aborting."
            exit 1
          fi

          echo "Installing AutoPkg..."
          sudo installer -pkg autopkg.pkg -target /
          echo "AutoPkg version:"
          autopkg version

      - name: Add AutoPkg recipe repositories
        run: |
          echo "Adding official AutoPkg recipes repo..."
          autopkg repo-add https://github.com/autopkg/recipes.git

          echo "Adding local vendored recipes folder..."
          autopkg repo-add ./recipes

          echo "Listing all recipes to confirm..."
          autopkg list-recipes

      - name: Set environment variable for custom processors (if any)
        run: |
          echo "AUTO_PKG_PROCESSOR_PATHS=$(pwd)/processors" >> $GITHUB_ENV

      # Munki recipe step is omitted for now since MUNKI_REPO is not configured.

      - name: Run VisualStudioCode.download.recipe with verbose output
        run: autopkg run VisualStudioCode.download.recipe --verbose

      - name: Debug - List all files in AutoPkg Cache Directory (non-failing)
        run: |
          RECIPE_CACHE_DIR=$(autopkg pref-read CacheDir)
          echo "AutoPkg Cache Directory: $RECIPE_CACHE_DIR"
          echo "Listing directory contents:"
          ls -la "$RECIPE_CACHE_DIR" || true
          echo "Listing all files recursively:"
          find "$RECIPE_CACHE_DIR" -type f || true

      - name: Find downloaded artifact (.intunemac, .pkg, .dmg, or .zip)
        id: find-artifact
        run: |
          RECIPE_CACHE_DIR=$(autopkg pref-read CacheDir)
          ARTIFACT=$(find "$RECIPE_CACHE_DIR" -type f \( -name "*.intunemac" -o -name "*.pkg" -o -name "*.dmg" -o -name "*.zip" \) | head -n 1)

          if [ -z "$ARTIFACT" ]; then
            echo "::error ::No package artifact (.intunemac, .pkg, .dmg, .zip) found in cache directory."
            exit 1
          fi

          echo "Found package artifact: $ARTIFACT"
          echo "ARTIFACT=$ARTIFACT" >> $GITHUB_ENV

      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-package
          path: ${{ env.ARTIFACT }}
          retention-days: 7
