name: Build Visual Studio Code Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show current directory and recipes folder for debug
        run: |
          echo "Current working directory:"
          pwd
          echo "Repository root contents:"
          ls -la
          echo "Recipes folder contents:"
          ls -la ./recipes

      - name: Clean AutoPkg cached recipe repos to avoid stale configs
        run: |
          echo "Cleaning old AutoPkg recipe repos..."
          rm -rf ~/Library/AutoPkg/RecipeRepos/*
          echo "Cleaned."

      - name: Download and install AutoPkg
        run: |
          echo "Downloading AutoPkg installer..."
          curl -L -o autopkg.pkg https://github.com/autopkg/autopkg/releases/download/v2.7.5/AutoPkg-2.7.5.pkg

          if [ ! -f autopkg.pkg ]; then
            echo "Error: AutoPkg installer package missing!"
            exit 1
          fi

          FILESIZE=$(stat -f%z autopkg.pkg)
          echo "Downloaded installer size: $FILESIZE bytes"

          if [ "$FILESIZE" -lt 100000 ]; then
            echo "Error: installer package is too small; likely failed download."
            exit 1
          fi

          echo "Installing AutoPkg..."
          sudo installer -pkg autopkg.pkg -target /
          autopkg version

      - name: Add AutoPkg recipe repositories
        run: |
          autopkg repo-add https://github.com/autopkg/recipes.git
          autopkg repo-add ./recipes
          autopkg list-recipes

      - name: Set environment variable for custom processors, if any
        run: echo "AUTO_PKG_PROCESSOR_PATHS=$(pwd)/processors" >> $GITHUB_ENV

      - name: Run VisualStudioCode.download.recipe only
        run: autopkg run VisualStudioCode.download.recipe --verbose

      - name: Find downloaded package artifact
        id: find-artifact
        run: |
          RECIPE_CACHE_DIR=$(autopkg pref-read CacheDir)
          echo "AutoPkg Cache Directory: $RECIPE_CACHE_DIR"

          ARTIFACT=$(find "$RECIPE_CACHE_DIR" -type f \( -name "*.intunemac" -o -name "*.pkg" -o -name "*.dmg" \) | head -n 1)

          if [ -z "$ARTIFACT" ]; then
            echo "::error ::No package artifact found in cache directory."
            exit 1
          fi

          echo "Package artifact found: $ARTIFACT"
          echo "ARTIFACT=$ARTIFACT" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-package
          path: ${{ env.ARTIFACT }}
          retention-days: 7
