name: Build VSCode .intunemac Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download and install AutoPkg
        run: |
          echo "Downloading AutoPkg installer..."
          curl -L -v -o autopkg.pkg https://github.com/autopkg/autopkg/releases/download/v2.7.5/AutoPkg-2.7.5.pkg

          if [ ! -f autopkg.pkg ]; then
            echo "Error: AutoPkg installer package not found!"
            exit 1
          fi

          FILESIZE=$(stat -f%z autopkg.pkg)
          echo "Downloaded AutoPkg installer size: $FILESIZE bytes"

          if [ "$FILESIZE" -lt 100000 ]; then
            echo "Error: Downloaded installer package is too small, likely a failed download."
            exit 1
          fi

          sudo installer -pkg autopkg.pkg -target /
          autopkg version

      - name: Validate and add AutoPkg recipe repos
        run: |
          set -e

          add_repo() {
            REPO_URL=$1
            REPO_NAME=$(basename "$REPO_URL" .git)
            echo "Checking access to $REPO_URL..."

            # Simple check: try to ls-remote to verify repo availability
            if git ls-remote "$REPO_URL" &> /dev/null; then
              echo "Repo accessible: $REPO_URL"
              # Remove previous cached repo if exists to avoid stale or corrupted cache
              autopkg repo-delete "$REPO_NAME" || true
              autopkg repo-add "$REPO_URL"
            else
              echo "::error ::Repository unreachable: $REPO_URL"
              exit 1
            fi
          }

          # Add official AutoPkg recipes repository
          add_repo https://github.com/autopkg/recipes.git

          # Add valdore86 community recipes repository
          add_repo https://github.com/valdore86-recipes/recipes.git

          # Add your custom local recipes folder - no remote URL check needed
          echo "Adding local recipes folder at ./recipes"
          autopkg repo-delete ./recipes || true
          autopkg repo-add ./recipes

          echo "Listing all AutoPkg recipes after adding repos:"
          autopkg list-recipes

      - name: Debug - List local recipes folder and file
        run: |
          echo "Contents of ./recipes folder:"
          ls -l ./recipes
          echo "Showing VSCode.intunemac.recipe content:"
          cat ./recipes/VSCode.intunemac.recipe || echo "Recipe file missing or unreadable"

      - name: Set environment variable for custom processors
        run: echo "AUTO_PKG_PROCESSOR_PATHS=$(pwd)/processors" >> $GITHUB_ENV

      - name: Run VSCode.intunemac.recipe
        run: autopkg run VSCode.intunemac.recipe --verbose

      - name: Find and set .intunemac artifact path
        id: find-artifact
        run: |
          RECIPE_CACHE_DIR=$(autopkg pref-read CacheDir)
          echo "RECIPE_CACHE_DIR=$RECIPE_CACHE_DIR"

          INTUNEMAC_FILE=$(find "$RECIPE_CACHE_DIR" -type f -name "*.intunemac" | head -n 1)
          if [ -z "$INTUNEMAC_FILE" ]; then
            echo "::error ::No .intunemac file found in the cache directory."
            exit 1
          fi

          echo "INTUNEMAC_FILE=$INTUNEMAC_FILE" >> $GITHUB_ENV
          echo "Found .intunemac file: $INTUNEMAC_FILE"

      - name: Upload .intunemac artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-intunemac
          path: ${{ env.INTUNEMAC_FILE }}
          retention-days: 7
