name: Build VSCode .intunemac Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download and install AutoPkg
        run: |
          echo "Downloading AutoPkg installer..."
          curl -L -v -o autopkg.pkg https://github.com/autopkg/autopkg/releases/download/v2.7.5/AutoPkg-2.7.5.pkg

          if [ ! -f autopkg.pkg ]; then
            echo "Error: AutoPkg installer package not found!"
            exit 1
          fi

          FILESIZE=$(stat -f%z autopkg.pkg)
          echo "Downloaded AutoPkg installer size: $FILESIZE bytes"

          if [ "$FILESIZE" -lt 100000 ]; then
            echo "Error: Downloaded installer package too small, likely a failed download."
            exit 1
          fi

          sudo installer -pkg autopkg.pkg -target /
          autopkg version

      - name: Add AutoPkg recipe repositories
        run: |
          # Clean any previous repo caches for a fresh start
          autopkg repo-delete com.github.autopkg.recipes || true
          autopkg repo-delete ./recipes || true

          # Add official AutoPkg recipes repo
          autopkg repo-add https://github.com/autopkg/recipes.git

          # Add your vendored local recipes repo
          autopkg repo-add ./recipes

          echo "Listing all available recipes after adding repos:"
          autopkg list-recipes

      - name: Debug - List local recipes directory and display recipe content
        run: |
          echo "Contents of ./recipes folder:"
          ls -l ./recipes
          echo "Displaying VSCode.intunemac.recipe content:"
          cat ./recipes/VSCode.intunemac.recipe || echo "Recipe file missing or unreadable"

      - name: Set environment variable for custom processors
        run: echo "AUTO_PKG_PROCESSOR_PATHS=$(pwd)/processors" >> $GITHUB_ENV

      - name: Run VSCode.intunemac.recipe
        run: autopkg run VSCode.intunemac.recipe --verbose

      - name: Find .intunemac artifact and set as environment variable
        id: find-artifact
        run: |
          RECIPE_CACHE_DIR=$(autopkg pref-read CacheDir)
          echo "AutoPkg cache directory: $RECIPE_CACHE_DIR"

          INTUNEMAC_FILE=$(find "$RECIPE_CACHE_DIR" -type f -name "*.intunemac" | head -n 1)
          if [ -z "$INTUNEMAC_FILE" ]; then
            echo "::error ::No .intunemac file found in cache directory."
            exit 1
          fi

          echo "INTUNEMAC_FILE=$INTUNEMAC_FILE" >> $GITHUB_ENV
          echo "Found .intunemac artifact at: $INTUNEMAC_FILE"

      - name: Upload .intunemac artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-intunemac
          path: ${{ env.INTUNEMAC_FILE }}
          retention-days: 7
