name: Build VSCode .intunemac Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download and install AutoPkg
        run: |
          curl -L -o autopkg.pkg https://github.com/autopkg/autopkg/releases/latest/download/AutoPkg-2.7.5.pkg
          # Check if file downloaded successfully and is of reasonable size
          if [ ! -f autopkg.pkg ]; then
            echo "Error: AutoPkg installer package not found!"
            exit 1
          fi
          FILESIZE=$(stat -f%z autopkg.pkg)
          echo "Downloaded AutoPkg installer size: $FILESIZE bytes"
          if [ "$FILESIZE" -lt 100000 ]; then
            echo "Error: Downloaded installer package is too small, likely a failed download."
            ls -l autopkg.pkg
            cat autopkg.pkg
            exit 1
          fi
          ls -l
          file autopkg.pkg
          sudo installer -pkg autopkg.pkg -target /
          autopkg --version

      - name: Add AutoPkg recipe repos
        run: |
          # Add official AutoPkg community recipes
          autopkg repo-add https://github.com/autopkg/recipes.git
          # Add your custom recipes from the checked out repo
          autopkg repo-add ./recipes

      - name: Set environment variable for custom processors
        run: echo "AUTO_PKG_PROCESSOR_PATHS=$(pwd)/processors" >> $GITHUB_ENV

      - name: Run VSCode.intunemac.recipe
        run: autopkg run VSCode.intunemac.recipe --verbose

      - name: Find and upload .intunemac artifact
        id: find-artifact
        run: |
          RECIPE_CACHE_DIR=$(autopkg pref-read CacheDir)
          echo "RECIPE_CACHE_DIR=$RECIPE_CACHE_DIR"
          INTUNEMAC_FILE=$(find "$RECIPE_CACHE_DIR" -name "*.intunemac" | head -n 1)
          if [ -z "$INTUNEMAC_FILE" ]; then
            echo "No .intunemac file found!"
            exit 1
          fi
          echo "INTUNEMAC_FILE=$INTUNEMAC_FILE" >> $GITHUB_ENV

      - name: Upload .intunemac artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-intunemac
          path: ${{ env.INTUNEMAC_FILE }}
          retention-days: 7
