name: Build Visual Studio Code Packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install AutoPkg
        run: |
          curl -L -o autopkg.pkg https://github.com/autopkg/autopkg/releases/download/v2.7.5/AutoPkg-2.7.5.pkg
          sudo installer -pkg autopkg.pkg -target /
          autopkg version

      - name: Add AutoPkg repos
        run: |
          autopkg repo-delete com.github.autopkg.recipes || true
          autopkg repo-add https://github.com/autopkg/recipes.git
          autopkg repo-delete ./recipes || true
          autopkg repo-add ./recipes
          autopkg list-recipes

      - name: Run VisualStudioCode.download.recipe
        run: autopkg run VisualStudioCode.download.recipe --verbose

      - name: Run VisualStudioCode.munki.recipe
        run: autopkg run VisualStudioCode.munki.recipe --verbose

      - name: Find generated package artifact
        id: find-artifact
        run: |
          RECIPE_CACHE_DIR=$(autopkg pref-read CacheDir)
          echo "AutoPkg CacheDir: $RECIPE_CACHE_DIR"
          ARTIFACT=$(find "$RECIPE_CACHE_DIR" -type f -name "*.pkg" -o -name "*.dmg" -o -name "*.intunemac" | head -n 1)
          if [ -z "$ARTIFACT" ]; then
            echo "No artifact found!"
            exit 1
          fi
          echo "ARTIFACT=$ARTIFACT" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-package
          path: ${{ env.ARTIFACT }}
          retention-days: 7
