name: Package VSCode for Intune vscode

on:
  workflow_dispatch:

jobs:
  package-vscode:
    runs-on: macos-latest
    steps:
      - name: Setup directories
        run: mkdir -p input output tools

      - name: Download VSCode ZIP
        run: |
          curl -L "https://update.code.visualstudio.com/latest/darwin/stable" -o "input/VSCode.zip"
          unzip -q input/VSCode.zip -d input/

      - name: Build VSCode PKG
        run: |
          pkgbuild --install-location /Applications \
          --component "input/Visual Studio Code.app" \
          "input/VSCode.pkg"

      - name: Download Intune App Wrapping Tool
        run: |
          curl -L "https://github.com/msintuneappshell/intune-app-wrapping-tool-macos/releases/latest/download/IntuneAppUtil" -o tools/IntuneAppUtil
          chmod +x tools/IntuneAppUtil

      - name: Wrap VSCode PKG into IntuneMac
        run: |
          ./tools/IntuneAppUtil -c input/VSCode.pkg -o output/VSCode.intunemac

      - name: Upload packaged files
        uses: actions/upload-artifact@v4
        with:
          name: vscode-packages
          path: |
            input/VSCode.pkg
            output/VSCode.intunemac
