name: Package VSCode DMG for Intune vscode

on:
  workflow_dispatch:

jobs:
  package-vscode-dmg:
    runs-on: macos-latest
    steps:
      # 1. Create directories
      - name: Setup directories
        run: mkdir -p input output tools

      # 2. Download VSCode DMG
      - name: Download VSCode DMG
        run: |
          curl -L "https://update.code.visualstudio.com/latest/darwin/stable" -o "input/VSCode.dmg"

      # 3. Download Intune App Wrapping Tool (more robust method)
      - name: Download Intune App Wrapping Tool
        run: |
          # Download the main branch source code archive directly
          curl -L "https://github.com/microsoft/shell-intune-app-utility/archive/main.tar.gz" -o tools/IntuneAppUtility.tar.gz
          
          # Extract the archive into the tools directory
          tar -xzf tools/IntuneAppUtility.tar.gz -C tools/
          
          # The executable is located inside the extracted folder (e.g., shell-intune-app-utility-main)
          # Move it to the top-level 'tools' directory and make it executable
          mv tools/shell-intune-app-utility-main/IntuneAppUtil tools/IntuneAppUtil
          chmod +x tools/IntuneAppUtil
          
          # Clean up the downloaded archive and the extracted source folder
          rm tools/IntuneAppUtility.tar.gz
          rm -rf tools/shell-intune-app-utility-main/

      # 4. Wrap VSCode DMG into Intune format
      - name: Wrap VSCode DMG
        run: |
          # The tool is now correctly downloaded and executable
          ./tools/IntuneAppUtil -c input/VSCode.dmg -o output/VSCode.intunemac

      # 5. Upload wrapped package as artifact
      - name: Upload Intune package
        uses: actions/upload-artifact@v4
        with:
          name: VSCode-intunemac
          path: output/VSCode.intunemac
