name: Package VSCode DMG for Intune

on:
  workflow_dispatch:

jobs:
  package-vscode-dmg:
    runs-on: macos-latest
    steps:
      # 1. Create directories
      - name: Setup directories
        run: mkdir -p input output tools

      # 2. Download VSCode DMG
      - name: Download VSCode DMG
        run: |
          curl -L "https://update.code.visualstudio.com/latest/darwin/stable" -o "input/VSCode.dmg"

      # 3. Download Intune App Wrapping Tool (robust method: clone repo)
      - name: Download Intune App Wrapping Tool
        run: |
          # Clone the repository containing the IntuneAppUtil script
          git clone https://github.com/microsoft/shell-intune-app-utility.git tools/intune-app-utility-repo
          
          # Move the IntuneAppUtil script to the main tools directory
          mv tools/intune-app-utility-repo/IntuneAppUtil tools/IntuneAppUtil
          
          # Make the script executable
          chmod +x tools/IntuneAppUtil
          
          # Clean up the cloned repository folder
          rm -rf tools/intune-app-utility-repo

      # 4. Wrap VSCode DMG into Intune format
      - name: Wrap VSCode DMG
        run: |
          # The tool is now correctly downloaded and executable
          ./tools/IntuneAppUtil -c input/VSCode.dmg -o output/VSCode.intunemac

      # 5. Upload wrapped package as artifact
      - name: Upload Intune package
        uses: actions/upload-artifact@v4
        with:
          name: VSCode-intunemac
          path: output/VSCode.intunemac
