name: Package VSCode for Intune (macOS-vscode)

on:
  workflow_dispatch:

jobs:
  package-vscode:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup folders
        run: mkdir -p input output

      - name: Download and extract VSCode
        run: |
          curl -L "https://update.code.visualstudio.com/latest/darwin/stable" -o input/VSCode.zip
          unzip -q input/VSCode.zip -d input/

      - name: Build a signed .pkg installer
        run: |
          pkgbuild \
            --install-location /Applications \
            --component "input/Visual Studio Code.app" \
            --sign "Developer ID Installer: Your Name (TEAMID)" \
            "output/VSCode.pkg"
          pkgutil --check-signature "output/VSCode.pkg"

      - name: Upload VSCode.pkg
        uses: actions/upload-artifact@v4
        with:
          name: vscode-pkg
          path: output/VSCode.pkg
