name: Get macOS App DMGs for Intune

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  vscode-dmg:
    runs-on: macos-latest
    steps:
      - name: Create directories
        run: |
          mkdir -p input output
      - name: Download latest VSCode macOS Universal (ZIP)
        run: |
          curl -L "https://update.code.visualstudio.com/latest/darwin-universal/stable" -o "input/VSCode.zip"
      - name: Unzip VSCode and move app bundle
        run: |
          # Create a temporary directory for unzipping to avoid cluttering 'input/' directly
          mkdir -p input/temp_unzip
          unzip -q input/VSCode.zip -d input/temp_unzip/

          # Find the .app bundle within the unzipped content. It's often one level deeper.
          # Use find to locate the actual app path.
          VSCODE_APP_FOUND_PATH=$(find input/temp_unzip -maxdepth 2 -name "Visual Studio Code.app" -type d | head -n 1)

          if [ -z "$VSCODE_APP_FOUND_PATH" ]; then
            echo "Error: Visual Studio Code.app not found in the unzipped directory."
            exit 1
          fi

          # Move the .app bundle directly into the top-level input directory
          mv "$VSCODE_APP_FOUND_PATH" "input/"

          # Clean up the temporary unzip directory
          rm -rf input/temp_unzip

          # Set VSCODE_APP_PATH to the definitive location (input/Visual Code.app)
          echo "VSCODE_APP_PATH=input/Visual Studio Code.app" | tee -a $GITHUB_ENV
      - name: Get VSCode version
        run: |
          # Now that the .app is at input/Visual Studio Code.app, defaults read should work
          VERSION=$(defaults read "input/Visual Studio Code.app/Contents/Info.plist" CFBundleShortVersionString)
          echo "VSCODE_VERSION=$VERSION" | tee -a $GITHUB_ENV
          echo "VSCode version: $VERSION"
      - name: Create VSCode DMG from app bundle
        run: |
          TEMP_DMG_PATH="output/VSCode-temp.dmg"
          hdiutil create -size 500m -fs HFS+ -volname "Visual Studio Code" -o "$TEMP_DMG_PATH"
          hdiutil attach "$TEMP_DMG_PATH" -nobrowse -quiet
          # Use the directly moved app bundle from input/
          cp -r "input/Visual Studio Code.app" "/Volumes/Visual Studio Code/"
          hdiutil detach "/Volumes/Visual Studio Code" -quiet
          mv "$TEMP_DMG_PATH" "output/VSCode-macOS-universal-$VSCODE_VERSION.dmg"
          echo "Created DMG: output/VSCode-macOS-universal-$VSCODE_VERSION.dmg"
      - name: Upload VSCode DMG as artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-dmg
          path: output/*.dmg
