name: Wrap VSCode DMG for Intune vscode

on:
  workflow_dispatch:

jobs:
  wrap-vscode-dmg:
    runs-on: macos-latest
    steps:
      - name: Set up directories
        run: mkdir -p input output tools

      # 1. Download VSCode DMG
      - name: Download VSCode DMG
        run: |
          curl -L "https://update.code.visualstudio.com/latest/darwin/stable" -o input/VSCode.dmg

      # 2. Mount DMG and copy .app
      - name: Mount and copy app
        run: |
          hdiutil attach input/VSCode.dmg -nobrowse -quiet
          cp -R "/Volumes/Visual Studio Code/Visual Studio Code.app" input/
          hdiutil detach "/Volumes/Visual Studio Code" -quiet

      # 3. Download Intune App Wrapping Tool
      - name: Download IntuneAppUtil
        run: |
          curl -L "https://github.com/msintuneappshell/intune-app-wrapping-tool-macos/releases/latest/download/IntuneAppUtil" -o tools/IntuneAppUtil
          chmod +x tools/IntuneAppUtil

      # 4. Wrap the DMG directly
      - name: Wrap DMG
        run: |
          ./tools/IntuneAppUtil -c input/VSCode.dmg -o output/VSCode.intunemac

      # 5. Upload wrapped file
      - name: Upload .intunemac
        uses: actions/upload-artifact@v4
        with:
          name: vscode-intunemac
          path: output/VSCode.intunemac
