name: Package VSCode DMG for Intune

on:
  workflow_dispatch:

jobs:
  package-vscode-dmg:
    runs-on: macos-latest
    steps:
      # 1. Create directories
      - name: Setup directories
        run: mkdir -p input output tools

      # 2. Download VSCode DMG
      - name: Download VSCode DMG
        run: |
          curl -L "https://update.code.visualstudio.com/latest/darwin/stable" -o "input/VSCode.dmg"

      # 3. Download Intune App Wrapping Tool
      - name: Download Intune App Wrapping Tool
        run: |
          curl -L "https://github.com/msintuneappshell/intune-app-wrapping-tool-macos/releases/latest/download/IntuneAppUtil" -o tools/IntuneAppUtil
          chmod +x tools/IntuneAppUtil

      # 4. Wrap VSCode DMG into Intune format
      - name: Wrap VSCode DMG
        run: |
          ./tools/IntuneAppUtil -c input/VSCode.dmg -o output/VSCode.intunemac

      # 5. Upload wrapped package as artifact
      - name: Upload Intune package
        uses: actions/upload-artifact@v4
        with:
          name: VSCode-intunemac
          path: output/VSCode.intunemac
