name: Download Microsoft Edge for macOS

on:
  workflow_dispatch:

jobs:
  download-edge:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p output

      - name: Download Microsoft Edge PKG
        run: |
          echo "Downloading Microsoft Edge PKG..."
          curl -L "https://go.microsoft.com/fwlink/?linkid=2093504" -o output/MicrosoftEdge.pkg

      - name: Extract PKG contents
        run: |
          mkdir -p output/pkg
          pkgutil --expand-full output/MicrosoftEdge.pkg output/pkg

      - name: Find and extract Edge.app
        run: |
          PAYLOAD_PKG=$(find output/pkg -name "*.pkg" | head -n 1)
          mkdir -p output/app
          pkgutil --expand-full "$PAYLOAD_PKG" output/app_pkg
          PAYLOAD_FILE=$(find output/app_pkg -name "Payload" | head -n 1)
          tar -xvf "$PAYLOAD_FILE" -C output/app

      - name: Get Bundle ID and Version
        run: |
          EDGE_APP_PATH=$(find output/app -name "Microsoft Edge.app" -type d | head -n 1)
          if [ -z "$EDGE_APP_PATH" ]; then
            echo "Microsoft Edge.app not found!"
            exit 1
          fi
          BUNDLE_ID=$(/usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" "$EDGE_APP_PATH/Contents/Info.plist")
          VERSION=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$EDGE_APP_PATH/Contents/Info.plist")
          echo "Bundle ID: $BUNDLE_ID"
          echo "Version: $VERSION"
