name: Download and Inspect macOS Edge PKG

on:
  workflow_dispatch:  # manual trigger

jobs:
  download-edge-pkg:
    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Create output directory
      run: mkdir -p output

    - name: Download Microsoft Edge PKG
      run: |
        EDGE_VERSION="stable"
        # Direct download URL for stable macOS pkg (update URL if needed)
        EDGE_PKG_URL="https://msedgesetup.azureedge.net/stable/MicrosoftEdgeStable.pkg"
        echo "Downloading Microsoft Edge PKG from $EDGE_PKG_URL"
        curl -L "$EDGE_PKG_URL" -o output/MicrosoftEdgeStable.pkg

    - name: Check downloaded PKG info (bundle ID etc.)
      run: |
        pkgutil --pkg-info output/MicrosoftEdgeStable.pkg || echo "Failed to read pkg info"

    - name: Extract bundle ID from installed app (if installed)
      run: |
        # Just for demonstration, if app installed at standard location
        if [ -d "/Applications/Microsoft Edge.app" ]; then
          echo "Bundle ID of installed Edge app:"
          defaults read "/Applications/Microsoft Edge.app/Contents/Info.plist" CFBundleIdentifier
        else
          echo "Microsoft Edge.app not installed on runner."
        fi

    - name: List output directory files
      run: ls -lh output
