name: Package Microsoft Edge as IntuneWin

on:
  workflow_dispatch:

jobs:
  build-intunewin:
    runs-on: windows-latest

    steps:
      - name: Create directories
        run: |
          New-Item -Path input -ItemType Directory
          New-Item -Path output -ItemType Directory

      - name: Download Microsoft Edge Offline Installer (Stable Channel)
        run: |
          Invoke-WebRequest -Uri "https://msedgesetup.azureedge.net/stable/117.0.2045.60/MicrosoftEdgeEnterpriseX64.msi" -OutFile "input\MicrosoftEdgeSetup.msi"

      - name: Download Microsoft Win32 Content Prep Tool v1.8.6
        run: |
          Invoke-WebRequest -Uri "https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/releases/download/v1.8.6/IntuneWinAppUtil.exe" -OutFile "IntuneWinAppUtil.exe"

      - name: Package using IntuneWinAppUtil
        run: |
          .\IntuneWinAppUtil.exe -c ".\input" -s "MicrosoftEdgeSetup.msi" -o ".\output" -q

      - name: Upload .intunewin package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: edge-intunewin
          path: output/*.intunewin
