name: Package Microsoft Edge for Intune (macOS)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare workspace
        run: |
          echo "Cleaning old files..."
          rm -rf output
          mkdir -p output/pkg

      - name: Download Microsoft Edge PKG
        run: |
          echo "Downloading Microsoft Edge PKG..."
          curl -L "https://go.microsoft.com/fwlink/?linkid=2093504" -o output/MicrosoftEdge.pkg

      - name: Extract PKG
        run: |
          echo "Extracting PKG..."
          rm -rf output/pkg   # Ensure no existing folder causes 'File exists' error
          pkgutil --expand-full output/MicrosoftEdge.pkg output/pkg

      - name: Download Intune App Wrapping Tool
        run: |
          echo "Downloading Intune App Wrapping Tool..."
          curl -L "https://github.com/msintuneappsdk/intune-app-wrapping-tool-mac/releases/latest/download/intune-app-wrapping-tool-mac.zip" -o output/wrapper.zip
          unzip -o output/wrapper.zip -d output

      - name: Wrap PKG into .intunemac
        run: |
          echo "Wrapping PKG into .intunemac..."
          chmod +x output/intune-app-wrapping-tool-mac
          ./output/intune-app-wrapping-tool-mac \
            -c output/MicrosoftEdge.pkg \
            -o output/MicrosoftEdge.intunemac

      - name: Upload packaged app as artifact
        uses: actions/upload-artifact@v4
        with:
          name: MicrosoftEdge-intunemac
          path: output/MicrosoftEdge.intunemac
