name: Package Microsoft Edge for macOS

on:
  workflow_dispatch:

jobs:
  package-edge:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p output

      - name: Download Microsoft Edge PKG
        run: |
          echo "Downloading Microsoft Edge PKG..."
          curl -L -o output/MicrosoftEdge.pkg "https://go.microsoft.com/fwlink/?linkid=2093504"

      - name: Get Microsoft Edge bundle ID
        run: |
          echo "Extracting bundle ID..."
          pkgutil --expand output/MicrosoftEdge.pkg output/pkg_content
          app_path=$(find output/pkg_content -name "Microsoft Edge.app" -type d | head -n 1)
          if [ -z "$app_path" ]; then
            echo "Microsoft Edge.app not found in PKG."
            exit 1
          fi
          bundle_id=$(/usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" "$app_path/Contents/Info.plist")
          echo "Bundle ID: $bundle_id"
          echo "BUNDLE_ID=$bundle_id" >> $GITHUB_ENV

      - name: Download Intune App Wrapping Tool
        run: |
          echo "Downloading Intune App Wrapping Tool..."
          curl -L -o output/wrapper.zip "https://github.com/msintuneappsdk/intune-app-wrapping-tool-mac/releases/latest/download/IntuneAppWrappingTool.zip"
          echo "Extracting Intune App Wrapping Tool..."
          unzip -o output/wrapper.zip -d output/wrapper
          chmod +x output/wrapper/IntuneAppUtil

      - name: Wrap Microsoft Edge PKG
        run: |
          echo "Wrapping Microsoft Edge PKG into .intunemac format..."
          ./output/wrapper/IntuneAppUtil -c output/MicrosoftEdge.pkg -o output -i "$BUNDLE_ID"

      - name: Upload wrapped app
        uses: actions/upload-artifact@v4
        with:
          name: MicrosoftEdge-intunemac
          path: output/*.intunemac
