name: Package Microsoft Edge for macOS

on:
  workflow_dispatch:

jobs:
  package-edge:
    runs-on: macos-latest
    steps:
      - name: Set up directories
        run: |
          rm -rf edge_pkg wrapped
          mkdir -p edge_pkg wrapped

      - name: Download Microsoft Edge for macOS (.pkg)
        run: |
          curl -L "https://go.microsoft.com/fwlink/?linkid=2069148" -o edge_pkg/MicrosoftEdge.pkg

      - name: Download Microsoft Intune App Wrapping Tool for Mac
        run: |
          curl -L "https://aka.ms/intune-app-wrapping-tool-mac" -o wrapped/IntuneAppUtil.zip
          unzip -q wrapped/IntuneAppUtil.zip -d wrapped
          chmod +x wrapped/IntuneAppUtil

      - name: Wrap Microsoft Edge PKG into IntuneMac
        run: |
          wrapped/IntuneAppUtil -c edge_pkg/MicrosoftEdge.pkg \
            -o wrapped/MicrosoftEdge.intunemac \
            -b com.microsoft.edgemac

      - name: Upload packaged Edge IntuneMac file
        uses: actions/upload-artifact@v4
        with:
          name: MicrosoftEdge-IntuneMac
          path: wrapped/MicrosoftEdge.intunemac
