name: Extract Edge PKG Bundle ID

on:
  workflow_dispatch:

jobs:
  extract-bundle-id:
    runs-on: macos-latest

    steps:
    - name: Create output directory
      run: mkdir -p output

    - name: Download Microsoft Edge PKG
      run: |
        EDGE_VERSION="stable"
        EDGE_URL="https://msedgesetup.azureedge.net/${EDGE_VERSION}/MicrosoftEdgeStable.pkg"
        curl -L $EDGE_URL -o output/MicrosoftEdgeStable.pkg

    - name: Expand PKG and extract bundle identifier
      run: |
        mkdir -p expanded_pkg
        pkgutil --expand output/MicrosoftEdgeStable.pkg expanded_pkg

        cd expanded_pkg
        if [ -f Payload ]; then
          mkdir payload_contents
          # Payload is gzip+cpio archive
          cat Payload | gzip -d | cpio -idmv
          # Find the first .app directory
          APP_PATH=$(find payload_contents -name "*.app" -type d | head -n 1)
          echo "Found app at $APP_PATH"
          echo "Bundle ID:"
          /usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" "$APP_PATH/Contents/Info.plist"
        else
          echo "No Payload found in package."
          exit 1
        fi
