- name: Set AutoPkg processor path
  run: |
    echo "Cloning Shell Intune App Utility for IntuneAppUtil processor..."
    git clone https://github.com/microsoft/shell-intune-app-utility.git tools/intune-app-utility-repo
    
    mkdir -p "$(autopkg pref-read RECIPE_REPO_DIR)"/com.github.autopkg.intuneprocessors/
    
    mv tools/intune-app-utility-repo/IntuneAppUtil "$(autopkg pref-read RECIPE_REPO_DIR)"/com.github.autopkg.intuneprocessors/IntuneAppUtil
    chmod +x "$(autopkg pref-read RECIPE_REPO_DIR)"/com.github.autopkg.intuneprocessors/IntuneAppUtil
    
    cat > "$(autopkg pref-read RECIPE_REPO_DIR)"/com.github.autopkg.intuneprocessors/IntuneAppUtil.py <<'EOF'
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
        <key>Processor</key>
        <string>IntuneAppUtil</string>
        <key>Arguments</key>
        <dict>
            <key>app_path</key>
            <string>%app_path%</string>
            <key>output_path</key>
            <string>%output_path%</string>
        </dict>
    </dict>
    </plist>
    EOF

    rm -rf tools/intune-app-utility-repo
    echo "IntuneAppUtil processor setup complete."
