- name: Create wrapper install script
  run: |
    cat <<'EOF' > input/run_homebrew_install.sh
#!/bin/bash
echo "Starting Homebrew installation via wrapper script..."
NONINTERACTIVE=1 /bin/bash "$(dirname "$0")/install_homebrew.sh"
if [ $? -ne 0 ]; then
  echo "Homebrew installation failed."
  exit 1
fi
echo "Homebrew installation completed successfully."
EOF
    chmod +x input/run_homebrew_install.sh
    echo "Wrapper script created."
