name: Package Homebrew Installer for Intune

on:
  workflow_dispatch:

jobs:
  package-intunemac:
    runs-on: macos-latest
    steps:
      - name: Prepare folders
        run: mkdir -p scripts output tools

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify install_homebrew.sh exists
        run: |
          if [ ! -f "install_homebrew.sh" ]; then
            echo "Error: install_homebrew.sh not found at repository root. Please commit it."
            exit 1
          fi

      - name: Copy install_homebrew.sh to scripts/
        run: cp install_homebrew.sh scripts/install_homebrew.sh

      - name: Create wrapper install script
        run: |
          cat <<'EOF' > scripts/run_homebrew_install.sh
          #!/bin/bash
          echo "Starting Homebrew installation via wrapper script..."
          NONINTERACTIVE=1 /bin/bash "$(dirname "$0")/install_homebrew.sh"
          if [ $? -ne 0 ]; then
            echo "Homebrew installation failed."
            exit 1
          fi
          echo "Homebrew installation completed successfully."
          EOF
          chmod +x scripts/run_homebrew_install.sh
          echo "Wrapper script created."

      - name: Checkout Intune App Wrapping Tool
        uses: actions/checkout@v3
        with:
          repository: microsoft/shell-intune-app-utility
          path: tools/intune-app-utility-repo

      - name: Prepare Intune App Utility
        run: |
          mv tools/intune-app-utility-repo/IntuneAppUtil tools/IntuneAppUtil
          chmod +x tools/IntuneAppUtil
          rm -rf tools/intune-app-utility-repo

      - name: Wrap script into .intunemac
        run: ./tools/IntuneAppUtil -c scripts/run_homebrew_install.sh -o output/HomebrewInstaller.intunemac

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: homebrew-installer-intunemac
          path: output/HomebrewInstaller.intunemac
          retention-days: 7
