name: Package Homebrew Installer for Intune

on:
  workflow_dispatch:

jobs:
  package-intunemac:
    runs-on: macos-latest
    steps:
      - name: Prepare folders
        run: |
          mkdir -p input output tools

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare install scripts
        run: |
          mkdir -p input
          # Ensure install_homebrew.sh is in the input directory
          # This assumes install_homebrew.sh is at the root of your Git repository
          if [ ! -f "install_homebrew.sh" ]; then # Check for it at root, not input/ initially
            echo "Error: install_homebrew.sh not found at repository root. Please ensure it's committed."
            exit 1
          fi
          cp install_homebrew.sh input/install_homebrew.sh # Copy from root to input/
          
          # Create the wrapper script.
          # The script content and the closing 'EOF' must start at the same column
          # as the 'cat' command itself.
          cat > input/run_homebrew_install.sh <<'EOF'
#!/bin/bash
echo "Starting Homebrew installation via wrapper script..."
NONINTERACTIVE=1 /bin/bash "$(dirname "$0")/install_homebrew.sh"
if [ $? -ne 0 ]; then
  echo "Homebrew installation failed."
  exit 1
fi
echo "Homebrew installation completed successfully."
EOF
          # Ensure the wrapper script is executable
          chmod +x input/run_homebrew_install.sh
          echo "Wrapper script created and made executable."

      - name: Download Intune App Wrapping Tool for macOS
        run: |
          echo "Cloning Intune App Utility repository..."
          git clone https://github.com/microsoft/shell-intune-app-utility.git tools/intune-app-utility-repo
          mv tools/intune-app-utility-repo/IntuneAppUtil tools/IntuneAppUtil
          chmod +x tools/IntuneAppUtil
          rm -rf tools/intune-app-utility-repo
          echo "Intune App Wrapping Tool downloaded and made executable."

      - name: Wrap script into .intunemac
        run: |
          echo "Wrapping run_homebrew_install.sh into .intunemac..."
          ./tools/IntuneAppUtil -c input/run_homebrew_install.sh -o output/HomebrewInstaller.intunemac
          echo "Created HomebrewInstaller.intunemac"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: homebrew-installer-intunemac
          path: output/HomebrewInstaller.intunemac
          retention-days: 7
