name: Package Homebrew Installer for Intune

on:
  workflow_dispatch: # Allows manual triggering of the workflow from GitHub UI

jobs:
  package-intunemac:
    runs-on: macos-latest # Requires a macOS runner to use native Apple tools

    steps:
      - name: Prepare folders
        run: |
          mkdir -p input output tools # Create directories for organization

      - name: Checkout repository
        uses: actions/checkout@v3 # Clones your repository into the runner's workspace

      - name: Prepare install scripts
        run: |
          # Ensure install_homebrew.sh is present in the input directory.
          # This assumes 'install_homebrew.sh' is committed at the root of your Git repository.
          if [ ! -f "install_homebrew.sh" ]; then
            echo "Error: install_homebrew.sh not found at repository root. Please ensure it's committed."
            exit 1
          fi
          cp install_homebrew.sh input/install_homebrew.sh # Copy the script into the 'input' folder

          # Create a wrapper script (run_homebrew_install.sh) that executes the actual Homebrew install script.
          # The NONINTERACTIVE=1 flag is crucial for silent installation during Intune deployment.
          # IMPORTANT: The script content must start on a NEW LINE after 'EOF' and be indented.
          # The final 'EOF' must be at the same indentation level as the 'cat' command.
          cat > input/run_homebrew_install.sh <<'EOF'
#!/bin/bash
echo "Starting Homebrew installation via wrapper script..."
NONINTERACTIVE=1 /bin/bash "$(dirname "$0")/install_homebrew.sh"
if [ $? -ne 0 ]; then
  echo "Homebrew installation failed."
  exit 1
fi
echo "Homebrew installation completed successfully."
EOF
          # Ensure the wrapper script is executable
          chmod +x input/run_homebrew_install.sh
          echo "Wrapper script 'run_homebrew_install.sh' created and made executable."

      - name: Download Intune App Wrapping Tool for macOS
        run: |
          echo "Cloning Intune App Utility repository for reliable download..."
          git clone https://github.com/microsoft/shell-intune-app-utility.git tools/intune-app-utility-repo

          echo "Moving IntuneAppUtil executable to tools/..."
          mv tools/intune-app-utility-repo/IntuneAppUtil tools/IntuneAppUtil

          chmod +x tools/IntuneAppUtil
          echo "IntuneAppUtil downloaded and made executable."

          echo "Cleaning up temporary git repository..."
          rm -rf tools/intune-app-utility-repo

      - name: Wrap script into .intunemac
        run: |
          echo "Wrapping input/run_homebrew_install.sh into output/HomebrewInstaller.intunemac..."
          ./tools/IntuneAppUtil -c input/run_homebrew_install.sh -o output/HomebrewInstaller.intunemac
          echo "HomebrewInstaller.intunemac created successfully."

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: homebrew-installer-intunemac
          path: output/HomebrewInstaller.intunemac
          retention-days: 7
