name: Package Homebrew Installer for Intune

on:
  workflow_dispatch:

jobs:
  package-intunemac:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare scripts folder and ensure executables
        run: |
          chmod +x scripts/install_homebrew.sh
          chmod +x scripts/run_homebrew_install.sh

      - name: Download Intune App Wrapping Tool for macOS
        run: |
          git clone https://github.com/microsoft/shell-intune-app-utility.git tools/intune-app-utility-repo
          mv tools/intune-app-utility-repo/IntuneAppUtil tools/IntuneAppUtil
          chmod +x tools/IntuneAppUtil
          rm -rf tools/intune-app-utility-repo

      - name: Wrap run_homebrew_install.sh script into .intunemac
        run: |
          ./tools/IntuneAppUtil -c scripts/run_homebrew_install.sh -o output/HomebrewInstaller.intunemac
          echo "Created HomebrewInstaller.intunemac"

      - name: Upload wrapped .intunemac artifact
        uses: actions/upload-artifact@v4
        with:
          name: homebrew-installer-intunemac
          path: output/HomebrewInstaller.intunemac
          retention-days: 7
