name: Build GitHub Desktop Package for macOS

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  github_desktop_macos:
    runs-on: macos-latest # This job runs on a macOS runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show current working directory and recipes folder for debug
        run: |
          echo "Current working directory:"
          pwd
          echo "Repository root contents:"
          ls -la
          echo "Recipes folder contents:"
          ls -la ./recipes || true # Add || true to prevent failure if folder is empty or not found

      - name: Clean AutoPkg cached recipe repositories
        run: |
          echo "Removing old AutoPkg recipe caches..."
          rm -rf ~/Library/AutoPkg/RecipeRepos/* || true
          echo "Cache cleanup done."

      - name: Download and install AutoPkg
        run: |
          echo "Downloading AutoPkg installer..."
          curl -L -o autopkg.pkg https://github.com/autopkg/autopkg/releases/download/v2.7.5/AutoPkg-2.7.5.pkg

          if [ ! -f autopkg.pkg ]; then
            echo "Error: AutoPkg installer package missing!"
            exit 1
          fi

          filesize=$(stat -f%z autopkg.pkg)
          echo "Installer package size: $filesize bytes"

          if [ "$filesize" -lt 100000 ]; then
            echo "Error: Installer package is suspiciously small; aborting."
            exit 1
          fi

          echo "Installing AutoPkg..."
          sudo installer -pkg autopkg.pkg -target /
          echo "AutoPkg version:"
          autopkg version

      - name: Add AutoPkg recipe repositories
        run: |
          echo "Adding official AutoPkg recipes repo..."
          autopkg repo-add https://github.com/autopkg/recipes.git
          echo "Listing all recipes to confirm..."
          autopkg list-recipes

      - name: Set environment variable for custom processors (if any)
        run: |
          echo "AUTO_PKG_PROCESSOR_PATHS=$(pwd)/processors" >> $GITHUB_ENV

      - name: Run GitHubDesktop.download.recipe and Extract Path
        id: run_and_extract_path
        run: |
          AUTOPKG_OUTPUT=$(autopkg run GitHubDesktop.download.recipe --verbose 2>&1)
          echo "$AUTOPKG_OUTPUT"

          GH_DESKTOP_ZIP_PATH=$(echo "$AUTOPKG_OUTPUT" | grep 'URLDownloader: Downloaded ' | awk '{print $NF}' | head -n 1 | xargs)

          if [ -z "$GH_DESKTOP_ZIP_PATH" ]; then
            echo "::error ::Could not extract GitHub Desktop ZIP installer path from AutoPkg output."
            echo "$AUTOPKG_OUTPUT"
            exit 1
          fi

          echo "Found GitHub Desktop ZIP installer at: $GH_DESKTOP_ZIP_PATH"
          echo "GH_DESKTOP_ZIP_PATH=$GH_DESKTOP_ZIP_PATH" >> $GITHUB_ENV

      - name: Extract GitHub Desktop.app from ZIP
        id: extract_app
        run: |
          APP_EXTRACT_DIR="/private/tmp/GitHubDesktopAppExtract_$(uuidgen)"
          echo "Extracting GitHub Desktop.app to: $APP_EXTRACT_DIR"
          mkdir -p "$APP_EXTRACT_DIR"

          unzip -q "${{ env.GH_DESKTOP_ZIP_PATH }}" -d "$APP_EXTRACT_DIR" || { echo "::error ::Failed to unzip GitHub Desktop archive."; exit 1; }

          GH_DESKTOP_APP_PATH=$(find "$APP_EXTRACT_DIR" -type d -name "GitHub Desktop.app" | head -n 1)

          if [ -z "$GH_DESKTOP_APP_PATH" ]; then
            echo "::error ::GitHub Desktop.app not found in extracted ZIP."
            ls -laR "$APP_EXTRACT_DIR" || true
            exit 1
          fi

          echo "Found GitHub Desktop.app at: $GH_DESKTOP_APP_PATH"
          echo "GH_DESKTOP_APP_PATH=$GH_DESKTOP_APP_PATH" >> $GITHUB_ENV
          echo "APP_EXTRACT_DIR=$APP_EXTRACT_DIR" >> $GITHUB_ENV

      - name: Create and Sign PKG from GitHub Desktop.app
        id: create_pkg
        env:
          DEVELOPER_ID_INSTALLER_CERT: ${{ secrets.DEVELOPER_ID_INSTALLER_CERT_NAME }}
        run: |
          RECIPE_CACHE_DIR="$HOME/Library/AutoPkg/Cache"
