name: Build Telegram Desktop macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      PATH: /opt/homebrew/opt/qt@5/bin:$PATH
      LDFLAGS: -L/opt/homebrew/opt/qt@5/lib
      CPPFLAGS: -I/opt/homebrew/opt/qt@5/include
      PKG_CONFIG_PATH: /opt/homebrew/opt/qt@5/lib/pkgconfig

    steps:
      - name: Install Homebrew, git, and dependencies
        run: |
          if ! command -v brew &> /dev/null; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
            eval "$(/opt/homebrew/bin/brew shellenv)"
          fi
          brew update
          brew install git qt@5 pkgconf cmake

      - name: Clone Telegram Desktop repository
        run: git clone --depth 1 https://github.com/telegramdesktop/tdesktop.git

      - name: Build Telegram Desktop
        run: |
          cd tdesktop
          mkdir -p build
          cd build
          cmake .. -DCMAKE_PREFIX_PATH=/opt/homebrew/opt/qt@5
          make -j$(sysctl -n hw.ncpu)

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: telegram-macos-build
          path: tdesktop/build
