name: Build Telegram Desktop macOS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v3

      - name: Clone Telegram Desktop repo
        run: |
          git clone --depth 1 https://github.com/telegramdesktop/tdesktop.git

      - name: Install dependencies with Homebrew
        run: |
          brew install qt@5 pkg-config
          # Set env for keg-only qt@5
          echo 'export PATH="/opt/homebrew/opt/qt@5/bin:$PATH"' >> $GITHUB_ENV
          echo 'export LDFLAGS="-L/opt/homebrew/opt/qt@5/lib"' >> $GITHUB_ENV
          echo 'export CPPFLAGS="-I/opt/homebrew/opt/qt@5/include"' >> $GITHUB_ENV
          echo 'export PKG_CONFIG_PATH="/opt/homebrew/opt/qt@5/lib/pkgconfig"' >> $GITHUB_ENV

      - name: Build Telegram Desktop
        shell: bash
        env:
          PATH: /opt/homebrew/opt/qt@5/bin:${{ env.PATH }}
          LDFLAGS: -L/opt/homebrew/opt/qt@5/lib
          CPPFLAGS: -I/opt/homebrew/opt/qt@5/include
          PKG_CONFIG_PATH: /opt/homebrew/opt/qt@5/lib/pkgconfig
        run: |
          cd tdesktop
          ./configure
          make -j$(sysctl -n hw.ncpu)

      - name: Upload Telegram app artifact
        uses: actions/upload-artifact@v4
        with:
          name: telegram-macos-app
          path: tdesktop/bin/Telegram.app
