name: MacOS Build Telegram Desktop

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          brew update
          brew install qt@5 pkg-config cmake ninja

      - name: Build Telegram Desktop
        run: |
          # Assuming you are in the Telegram repo root
          # Example: Configure and build with CMake and Ninja
          mkdir -p build
          cd build
          cmake -G Ninja -DCMAKE_PREFIX_PATH=$(brew --prefix qt@5) ..
          ninja

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: telegram-macos-app
          path: build/Telegram.app
