name: Package VSCode macOS App as IntuneMac and DMG

on:
  workflow_dispatch:

jobs:
  package-vscode:
    runs-on: macos-latest
    steps:
      - name: Setup directories
        run: |
          mkdir -p input output tools dmg_files

      - name: Download VSCode DMG
        run: |
          curl -L "https://update.code.visualstudio.com/latest/darwin/stable" -o "input/VSCode.dmg"

      - name: Mount VSCode DMG and copy .app
        run: |
          set -eux
          MOUNTINFO=$(hdiutil attach input/VSCode.dmg -nobrowse)
          echo "Mount info:"
          echo "$MOUNTINFO"
          MOUNTPOINT=$(echo "$MOUNTINFO" | grep "/Volumes" | awk '{print $3}')
          echo "Mounted at: $MOUNTPOINT"

          if [ -z "$MOUNTPOINT" ]; then
            echo "Error: Could not find mount point for the DMG."
            exit 1
          fi

          cp -R "$MOUNTPOINT/Visual Studio Code.app" input/
          hdiutil detach "$MOUNTPOINT" -quiet

      - name: Download Intune App Wrapping Tool
        run: |
          curl -L "https://github.com/msintuneappshell/intune-app-wrapping-tool-macos/releases/latest/download/IntuneAppUtil" -o tools/IntuneAppUtil
          chmod +x tools/IntuneAppUtil

      - name: Wrap VSCode .app into .intunemac
        run: |
          ./tools/IntuneAppUtil -c input/Visual\ Studio\ Code.app -o output/VSCode.intunemac

      - name: Upload artifacts (DMG and Intunemac)
        uses: actions/upload-artifact@v4
        with:
          name: vscode-packages
          path: |
            input/VSCode.dmg
            output/VSCode.intunemac
