name: Package Google Chrome macOS DMG

on:
  workflow_dispatch:

jobs:
  package-chrome:
    runs-on: macos-latest
    steps:
      - name: Create directories for Chrome packaging
        run: |
          mkdir -p output

      - name: Download latest Google Chrome macOS DMG
        run: |
          echo "Downloading latest Google Chrome DMG..."
          curl -L "https://dl.google.com/chrome/mac/universal/stable/GGRO/googlechrome.dmg" -o "output/GoogleChrome-latest.dmg"
          echo "Downloaded Google Chrome DMG to output/GoogleChrome-latest.dmg"

      - name: Get Chrome bundle ID and version from DMG
        run: |
          set -eux
          DMG_PATH="output/GoogleChrome-latest.dmg"
          
          echo "Attaching DMG for info check..."
          MOUNT_OUTPUT=$(hdiutil attach "$DMG_PATH" -nobrowse -noverify)
          echo "hdiutil attach output:"
          echo "$MOUNT_OUTPUT"

          MOUNTPOINT=$(echo "$MOUNT_OUTPUT" | grep '/Volumes/' | head -n 1 | sed -E 's/.*(\/Volumes\/.*)/\1/')
          echo "Mounted DMG at: $MOUNTPOINT"

          if [ -z "$MOUNTPOINT" ]; then
            echo "Error: Could not find mount point for Google Chrome DMG."
            exit 1
          fi

          BUNDLE_ID=$(defaults read "$MOUNTPOINT/Google Chrome.app/Contents/Info.plist" CFBundleIdentifier || echo "unknown")
          VERSION=$(defaults read "$MOUNTPOINT/Google Chrome.app/Contents/Info.plist" CFBundleShortVersionString || echo "unknown")

          echo "CHROME_BUNDLE_ID=$BUNDLE_ID" >> $GITHUB_ENV
          echo "CHROME_VERSION=$VERSION" >> $GITHUB_ENV

          echo "Google Chrome Bundle ID: $BUNDLE_ID"
          echo "Google Chrome version: $VERSION"

          echo "Detaching DMG..."
          hdiutil detach "$MOUNTPOINT" -quiet
          echo "DMG detached."

      - name: Rename Chrome DMG with version
        run: |
          FINAL_DMG="output/GoogleChrome-macOS-$CHROME_VERSION.dmg"
          mv "output/GoogleChrome-latest.dmg" "$FINAL_DMG"
          echo "Renamed DMG to: $FINAL_DMG"

      - name: Upload Chrome DMG as artifact
        uses: actions/upload-artifact@v4
        with:
          name: google-chrome-macos-dmg
          path: output/*.dmg
          retention-days: 7
