name: Download Slack DMG and Extract Bundle ID

on:
  workflow_dispatch:

jobs:
  slack-dmg:
    runs-on: macos-latest

    steps:
    - name: Create output directory
      run: mkdir -p output

    - name: Download Slack DMG
      run: |
        SLACK_URL="https://downloads.slack-edge.com/releases/macos/4.34.152/prod/x64/Slack-4.34.152-macOS.dmg"
        echo "Downloading Slack from $SLACK_URL"
        curl -L "$SLACK_URL" -o output/Slack.dmg

    - name: Mount Slack DMG
      id: mount
      run: |
        echo "Mounting Slack DMG..."
        MOUNT_DIR=$(hdiutil attach output/Slack.dmg -nobrowse -quiet | grep '/Volumes/' | awk '{print $3}')
        echo "MOUNT_DIR=$MOUNT_DIR" >> $GITHUB_OUTPUT

    - name: Copy Slack.app to output directory
      run: |
        cp -R "${{ steps.mount.outputs.MOUNT_DIR }}/Slack.app" output/

    - name: Unmount Slack DMG
      run: |
        echo "Unmounting Slack DMG..."
        hdiutil detach "${{ steps.mount.outputs.MOUNT_DIR }}" -quiet

    - name: Extract Bundle Identifier from Slack.app
      run: |
        /usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" output/Slack.app/Contents/Info.plist

    - name: Upload Slack.app and output files
      uses: actions/upload-artifact@v4
      with:
        name: slack-macos-app
        path: output/Slack.app
