name: Package macOS VSCode as IntuneMac

on:
  workflow_dispatch:

jobs:
  package-vscode:
    runs-on: macos-latest
    steps:
      - name: Setup directories
        run: |
          mkdir -p input output tools

      - name: Download VSCode DMG
        run: |
          curl -L "https://update.code.visualstudio.com/latest/darwin/stable" -o input/VSCode.dmg

      - name: Mount VSCode DMG and copy .app
        run: |
          MOUNTPOINT=$(hdiutil attach input/VSCode.dmg -nobrowse -quiet | grep "/Volumes" | awk '{print $3}')
          echo "Mounted at: $MOUNTPOINT"
          cp -R "$MOUNTPOINT/Visual Studio Code.app" input/
          hdiutil detach "$MOUNTPOINT" -quiet

      - name: Create VSCode pkg installer
        run: |
          pkgbuild --install-location /Applications --component "input/Visual Studio Code.app" input/VSCode.pkg

      - name: Download Intune App Wrapping Tool
        run: |
          curl -L -o tools/IntuneAppUtil "https://github.com/msintuneappshell/intune-app-wrapping-tool-macos/releases/latest/download/IntuneAppUtil"
          chmod +x tools/IntuneAppUtil

      - name: Wrap VSCode pkg to intunemac
        run: |
          ./tools/IntuneAppUtil -c input/VSCode.pkg -o output/VSCode.intunemac

      - name: Upload VSCode intunemac artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-intunemac
          path: output/VSCode.intunemac
