name: Wrap macOS DMG to Intune format

on:
  workflow_dispatch:

jobs:
  wrap-apps:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up directories
        run: |
          for dir in input output tools dmg_files; do
            [ -f "$dir" ] && rm -f "$dir"
            mkdir -p "$dir"
          done

      - name: Download IntuneAppUtil tool
        run: |
          curl -L -o tools/IntuneAppUtil "https://github.com/msintuneappshell/intune-app-wrapping-tool-macos/releases/latest/download/IntuneAppUtil"
          chmod +x tools/IntuneAppUtil
          echo "Downloaded IntuneAppUtil"

      # Optional: Download example .dmg file if none exists, remove if you commit your own DMGs
      - name: Add example .dmg file (optional)
        run: |
          if [ ! "$(ls -A dmg_files)" ]; then
            curl -L -o dmg_files/example.dmg "https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg"
          else
            echo "dmg_files directory is not empty, skipping download."
          fi

      - name: Wrap all .dmg files to .intunemac format
        run: |
          for dmg in dmg_files/*.dmg; do
            app_name=$(basename "$dmg" .dmg)
            echo "Wrapping $dmg..."
            ./tools/IntuneAppUtil -c "$dmg" -o output/
          done

      - name: Upload wrapped .intunemac files
        uses: actions/upload-artifact@v4
        with:
          name: wrapped-intunemac-apps
          path: output/*.intunemac

      - name: Upload original .dmg files
        uses: actions/upload-artifact@v4
        with:
          name: dmg-source-files
          path: dmg_files/*.dmg
