name: Package Slack for macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Create output directories
        run: |
          mkdir -p output wrapped slack_mount

      - name: Download Slack DMG
        run: |
          SLACK_URL="https://downloads.slack-edge.com/releases/macos/Slack-latest.dmg"
          echo "Downloading Slack from $SLACK_URL"
          curl -L "$SLACK_URL" -o output/Slack.dmg

      - name: Mount Slack DMG and copy Slack.app
        run: |
          echo "Mounting Slack DMG..."
          MOUNT_POINT=$(hdiutil attach output/Slack.dmg -nobrowse -quiet | grep Volumes | awk '{print $3}')
          echo "Copying Slack.app to output directory..."
          cp -R "$MOUNT_POINT/Slack.app" output/
          hdiutil detach "$MOUNT_POINT" -quiet

      - name: Download and extract IntuneAppUtil
        run: |
          echo "Downloading IntuneAppUtil DMG..."
          curl -L "https://aka.ms/intune-app-wrapping-tool-mac" -o wrapped/IntuneAppUtil.dmg
          echo "Mounting IntuneAppUtil DMG..."
          MOUNT_POINT=$(hdiutil attach wrapped/IntuneAppUtil.dmg -nobrowse -quiet | grep Volumes | awk '{print $3}')
          echo "Copying IntuneAppUtil binary..."
          cp "$MOUNT_POINT/IntuneAppUtil" wrapped/IntuneAppUtil
          chmod +x wrapped/IntuneAppUtil
          hdiutil detach "$MOUNT_POINT" -quiet

      - name: Wrap Slack.app as .intunemac
        run: |
          ./wrapped/IntuneAppUtil -c output/Slack.app -o output -i "com.tinyspeck.slackmacgap"

      - name: List output files
        run: ls -lh output
