name: Package VSCode macOS app

on:
  workflow_dispatch:

jobs:
  package-vscode:
    runs-on: macos-latest
    steps:
      - name: Setup directories
        run: |
          mkdir -p input output

      - name: Download VSCode DMG
        run: |
          curl -L "https://update.code.visualstudio.com/latest/darwin/stable" -o input/VSCode.dmg

      - name: Mount VSCode DMG and copy .app bundle
        run: |
          set -eux
          MOUNTINFO=$(hdiutil attach input/VSCode.dmg -nobrowse -quiet)
          echo "Mount info:"
          echo "$MOUNTINFO"
          MOUNTPOINT=$(echo "$MOUNTINFO" | grep "/Volumes" | awk '{print $3}')
          echo "Mounted at: $MOUNTPOINT"

          if [ -z "$MOUNTPOINT" ]; then
            echo "Error: Could not find mount point for the DMG."
            exit 1
          fi

          cp -R "$MOUNTPOINT/Visual Studio Code.app" input/
          hdiutil detach "$MOUNTPOINT" -quiet

      - name: Build pkg installer for VSCode
        run: |
          pkgbuild --install-location /Applications --component "input/Visual Studio Code.app" "input/VSCode.pkg"

      # Optional: wrap pkg for Intune (if you have IntuneAppUtil ready)
      # - name: Download Intune App Wrapping Tool
      #   run: |
      #     curl -L "https://github.com/msintuneappshell/intune-app-wrapping-tool-macos/releases/latest/download/IntuneAppUtil" -o tools/IntuneAppUtil
      #     chmod +x tools/IntuneAppUtil
      #
      # - name: Wrap VSCode.pkg as Intune package
      #   run: |
      #     ./tools/IntuneAppUtil -c input/VSCode.pkg -o output/VSCode.intunemac

      - name: Upload DMG and PKG as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vscode-packages
          path: |
            input/VSCode.dmg
            input/VSCode.pkg
