name: Wrap macOS DMG to Intune format dmt+pkg

on:
  workflow_dispatch:

jobs:
  wrap-apps:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up directories
        run: |
          mkdir -p input output tools dmg_files

      - name: Download IntuneAppUtil tool
        run: |
          curl -L -o tools/IntuneAppUtil "https://github.com/msintuneappshell/intune-app-wrapping-tool-macos/releases/latest/download/IntuneAppUtil"
          chmod +x tools/IntuneAppUtil
          echo "Downloaded IntuneAppUtil"

      - name: Add example .dmg file (optional)
        run: |
          echo "You can remove this step once you commit your own .dmg files"
          curl -L -o dmg_files/example.dmg "https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg"

      - name: Wrap all .dmg files to .intunemac format
        run: |
          for dmg in dmg_files/*.dmg; do
            app_name=$(basename "$dmg" .dmg)
            echo "Wrapping $dmg..."
            ./tools/IntuneAppUtil -c "$dmg" -o output/
          done

      - name: Upload wrapped .intunemac files
        uses: actions/upload-artifact@v4
        with:
          name: wrapped-intunemac-apps
          path: output/*.intunemac

      - name: Upload original .dmg files
        uses: actions/upload-artifact@v4
        with:
          name: dmg-source-files
          path: dmg_files/*.dmg
