name: Download and Extract Node.js Tarball

on:
  workflow_dispatch:

jobs:
  download-node:
    runs-on: macos-latest
    steps:
      - name: Setup output folder
        run: mkdir -p output

      - name: Get latest Node.js LTS version
        id: get_version
        run: |
          NODE_INDEX=$(curl -s "https://nodejs.org/dist/index.json")
          LTS_VERSION_FULL=$(echo "$NODE_INDEX" | jq -r '.[] | select(.lts) | .version' | sort -V | tail -n 1)
          echo "LTS_VERSION_FULL=$LTS_VERSION_FULL" >> $GITHUB_ENV
          echo "LTS_VERSION_FULL=$LTS_VERSION_FULL"

      - name: Download and extract Node.js tarball
        run: |
          set -eux
          ARCH=$(uname -m)
          if [[ "$ARCH" == "arm64" ]]; then
            NODE_ARCH="darwin-arm64"
          elif [[ "$ARCH" == "x86_64" ]]; then
            NODE_ARCH="darwin-x64"
          else
            echo "Unsupported architecture: $ARCH"
            exit 1
          fi

          TAR_FILE="node-${LTS_VERSION_FULL}-${NODE_ARCH}.tar.xz"
          DOWNLOAD_URL="https://nodejs.org/dist/${LTS_VERSION_FULL}/${TAR_FILE}"

          echo "Downloading $DOWNLOAD_URL"
          curl --fail -L "$DOWNLOAD_URL" -o "output/${TAR_FILE}"

          echo "Extracting Node.js tarball"
          tar -xf "output/${TAR_FILE}" -C output

          echo "Node.js extracted to output/node-${LTS_VERSION_FULL}-${NODE_ARCH}"
      
      - name: List output directory
        run: ls -l output
