name: Slack Desktop (Windows) Intune MSIX Package

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  package-slack-msix: # Renamed job to reflect MSIX packaging
    runs-on: windows-latest # This job runs on a Windows runner

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4 # Check out your repository code

      - name: 📂 Create working directories
        shell: pwsh
        run: |
          Write-Host "Creating necessary directories..."
          New-Item -ItemType Directory -Path ".\input" -ErrorAction SilentlyContinue
          New-Item -ItemType Directory -Path ".\output" -ErrorAction SilentlyContinue
          New-Item -ItemType Directory -Path ".\temp" -ErrorAction SilentlyContinue # Temp for manifest extraction
          Write-Host "Directories created."

      - name: 📥 Download Slack MSIX installer
        shell: pwsh
        run: |
          # Option 1 (Recommended): Use Slack's official MSIX download link.
          # This URL is designed to trigger an MSIX download from Slack's servers.
          # It should handle redirects correctly, but verify its behavior.
          $msixUrl = "https://slack.com/downloads/instructions/windows?ddl=1&build=win64_msix"
          
          # Option 2 (Alternative): If you have the MSIX stored in a secure, accessible location (e.g., Azure Blob Storage, internal file share)
          # Replace the URL below with your actual direct download link if you host it.
          # Example: $msixUrl = "https://your-company-storage.com/path/to/Slack-win64.msix"
          
          # Option 3 (Less Ideal for Binaries, but viable): If you commit the MSIX directly to your GitHub repository
          # You would comment out this entire 'Download Slack MSIX installer' step and
          # ensure the MSIX is committed to '.\input\slack-desktop-win64.msix'
          # A subsequent step would then just verify its presence, not download it.

          $outputFile = ".\input\slack-desktop-win64.msix" # Naming it directly as .msix
          Write-Host "Downloading Slack MSIX from $msixUrl to $outputFile..."
          try {
            Invoke-WebRequest -Uri $msixUrl -OutFile $outputFile -MaximumRedirection 5
            
            if (-not (Test-Path $outputFile)) {
              throw "Downloaded file not found at $outputFile."
            }
            # Verify the file is an MSIX (or similar package type)
            if ((Get-Item $outputFile).Extension -notin @(".msix", ".appx", ".appxbundle")) {
              Write-Warning "Downloaded file does not have a typical MSIX/APPX extension. Please verify."
            }
            $fileSize = (Get-Item $outputFile).Length
            Write-Host "Installer package size: $fileSize bytes."
            if ($fileSize -lt 10000000) { # Adjust minimum expected size for an MSIX package
              Write-Warning "Warning: Downloaded MSIX package is suspiciously small; please verify the download."
            }
            Write-Host "✅ Slack MSIX installer downloaded successfully."
          } catch {
            Write-Error "❌ Failed to download Slack MSIX installer: $($_.Exception.Message)"
            exit 1
          }

      - name: 🔎 Get Slack MSIX version from manifest
        id: get_version
        shell: pwsh
        run: |
          $msixPath = ".\input\slack-desktop-win64.msix"
          $tempManifestDir = ".\temp\manifest"
          New-Item -ItemType Directory -Path $tempManifestDir -ErrorAction SilentlyContinue

          if (-not (Test-Path $msixPath)) {
            Write-Error "❌ Slack MSIX installer not found at '$msixPath' for version extraction."
            exit 1
          }

          Write-Host "Extracting AppxManifest.xml from MSIX package..."
          try {
            # Use Expand-Archive to extract the manifest (or just the whole package to temp)
            # MSIX/APPX packages are essentially ZIP files, but PowerShell's built-in
            # Expand-Archive might not correctly handle them for manifest extraction directly.
            # We'll use a more direct method by treating it as a ZIP for manifest.
            Add-Type -AssemblyName System.IO.Compression.FileSystem
            [System.IO.Compression.ZipFile]::ExtractToDirectory($msixPath, $tempManifestDir)
          } catch {
            Write-Error "❌ Failed to extract MSIX package to temporary directory. Error: $($_.Exception.Message)"
            exit 1
          }

          $manifestPath = "$tempManifestDir\AppxManifest.xml"
          if (-not (Test-Path $manifestPath)) {
            Write-Error "❌ AppxManifest.xml not found within the extracted MSIX package at '$manifestPath'."
            exit 1
          }

          Write-Host "Parsing AppxManifest.xml for version..."
          $xml = [xml](Get-Content $manifestPath)
          $version = $xml.Package.Identity.Version
          
          if ([string]::IsNullOrEmpty($version)) {
            Write-Error "❌ Could not extract version from AppxManifest.xml. Version attribute missing."
            exit 1
          }

          # Set SLACK_VERSION as an environment variable for subsequent steps
          echo "SLACK_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append
          Write-Host "✅ Detected Slack MSIX version from manifest: $version"

      - name: 📦 Rename Slack MSIX package
        shell: pwsh
        run: |
          $originalFile = ".\input\slack-desktop-win64.msix"
          $outputFolder = ".\output"
          $slackVersion = $env:SLACK_VERSION

          # The check for 'Unknown' version is now less likely to trigger if manifest parsing is successful.
          if ($slackVersion -eq "Unknown" -or [string]::IsNullOrEmpty($slackVersion)) {
              Write-Error "❌ Cannot rename package: Slack version could not be reliably extracted. Please check the download URL or manifest."
              exit 1
          }

          if (-not (Test-Path $originalFile)) { # Added robustness check
              Write-Error "❌ Slack MSIX package not found for moving and renaming."
              exit 1
          }

          $newName = "Slack-win-x64-${slackVersion}.msix"
          $destinationPath = "$outputFolder\$newName"

          Write-Host "Moving and renaming '$originalFile' to '$destinationPath'..."
          # FIX: Use Move-Item when changing directory and renaming simultaneously
          Move-Item -Path $originalFile -Destination $destinationPath -Force

          $msixPackagePath = $destinationPath
          Write-Host "✅ Slack MSIX package prepared successfully: $msixPackagePath" # Re-added Write-Host
          echo "SLACK_MSIX_PACKAGE_PATH=$msixPackagePath" | Out-File -FilePath $env:GITHUB_ENV -Append # Set as env var

      # The 'Generate Intune App Details File for MSIX' step and its artifact upload are commented out as requested.

      - name: ⬆️ Upload Slack .msix package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Slack-Intune-MSIX-Package
          path: output\*.msix # Upload the generated .msix file
          retention-days: 7

      - name: 🧹 Clean up temporary directories
        if: always() # Run even if previous steps failed
        shell: pwsh
        run: |
          Write-Host "Cleaning up temporary directories..."
          Remove-Item -Path ".\input", ".\output", ".\temp" -Recurse -Force -ErrorAction SilentlyContinue # Include temp dir in cleanup
          Write-Host "Cleanup complete."
