name: Package Slack with IntuneBrew

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-package:
    runs-on: macos-latest
    steps:
      - name: Checkout repo (optional)
        uses: actions/checkout@v4

      - name: Install Go
        run: |
          brew install go
          go version

      - name: Clone IntuneBrew repo
        run: git clone https://github.com/joshuaavalon/IntuneBrew.git IntuneBrew

      - name: Build IntuneBrew CLI
        run: |
          cd IntuneBrew/cmd/intunebrew
          GO111MODULE=off go build -o intunebrew
          chmod +x intunebrew
          sudo mv intunebrew /usr/local/bin/
          intunebrew --version

      - name: Download Slack DMG
        run: |
          curl -L -o Slack.dmg "https://downloads.slack-edge.com/releases/macos/Slack-4.41.150-macOS.dmg"

      - name: Package Slack as .intunemac
        run: |
          intunebrew package \
            --source ./Slack.dmg \
            --output ./Slack.intunemac \
            --app-name "Slack" \
            --app-version "4.41.150" \
            --bundle-id "com.tinyspeck.slackmacgap"

      - name: Upload packaged app artifact
        uses: actions/upload-artifact@v4
        with:
          name: slack-intunemac-package
          path: ./Slack.intunemac
