name: Package macOS App for Intune

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build-package:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install IntuneBrew CLI manually
        run: |
          curl -sSL https://github.com/intune/intunebrew/releases/latest/download/intunebrew-macos.tar.gz | tar -xz -C /usr/local/bin
          chmod +x /usr/local/bin/intunebrew
          intunebrew --version

      - name: Download Slack DMG
        run: |
          curl -L -o Slack.dmg "https://downloads.slack-edge.com/releases/macos/Slack-4.41.150-macOS.dmg"

      - name: Package Slack as .intunemac
        run: |
          intunebrew package \
            --source ./Slack.dmg \
            --output ./Slack.intunemac \
            --app-name "Slack" \
            --app-version "4.41.150" \
            --bundle-id "com.tinyspeck.slackmacgap"

      - name: Upload packaged app artifact
        uses: actions/upload-artifact@v4
        with:
          name: slack-intunemac-package
          path: ./Slack.intunemac
