name: Build Slack Windows Package

on:
  workflow_dispatch:

jobs:
  slack:
    runs-on: windows-latest
    steps:
      - name: Create directories
        run: |
          New-Item -Path input -ItemType Directory -Force
          New-Item -Path output -ItemType Directory -Force

      - name: Download latest Slack for Windows installer
        shell: pwsh
        run: |
          $downloadUrl = "https://slack.com/ssb/download-win64"
          Write-Host "Downloading Slack from: $downloadUrl"
          Invoke-WebRequest -Uri $downloadUrl -OutFile "input\\SlackSetup.exe"

      - name: Get Slack installer version and set as environment variable
        shell: pwsh
        run: |
          $version = (Get-Item "input\\SlackSetup.exe").VersionInfo.ProductVersion
          Write-Host "Slack installer version: $version"
          echo "SLACK_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Download Microsoft Win32 Content Prep Tool
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/raw/2d0afcf7c1faf9c0f7dbd6db9c90b19f5dfec994/IntuneWinAppUtil.exe" -OutFile "IntuneWinAppUtil.exe"
          if (-not (Test-Path "IntuneWinAppUtil.exe")) {
              Write-Error "IntuneWinAppUtil.exe not downloaded."
              exit 1
          }

      - name: Package Slack using IntuneWinAppUtil
        shell: pwsh
        run: |
          .\IntuneWinAppUtil.exe -c ".\input" -s "SlackSetup.exe" -o ".\output" -q
          $originalFileName = "output\\SlackSetup.intunewin"
          $newName = "Slack-win-x64-$env:SLACK_VERSION.intunewin"
          Rename-Item -Path $originalFileName -NewName $newName -Force
          Write-Host "Renamed $originalFileName to $newName"

      - name: Upload Slack package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: slack-intunewin
          path: output/*.intunewin
