name: Package Google Chrome as IntuneWin

on:
  workflow_dispatch:

jobs:
  build-intunewin:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create directories
        run: |
          New-Item -Path input -ItemType Directory
          New-Item -Path output -ItemType Directory

      - name: Download Google Chrome Offline Installer (Enterprise)
        run: |
          Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/375.126/chrome_installer.exe" -OutFile "input\ChromeSetup.exe"

      - name: Check IntuneWinAppUtil.zip existence
        run: |
          Test-Path '.github\workflows\IntuneWinAppUtil.zip'
          Get-ChildItem .github\workflows\

      - name: Extract IntuneWinAppUtil.zip
        run: |
          Expand-Archive -Path '.github\workflows\IntuneWinAppUtil.zip' -DestinationPath '.' -Force

      - name: Package using IntuneWinAppUtil
        run: |
          .\IntuneWinAppUtil.exe -c ".\input" -s "ChromeSetup.exe" -o ".\output" -q

      - name: Upload .intunewin package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-intunewin
          path: output/*.intunewin
