jobs:
  slack:
    runs-on: windows-latest
    steps:
      - name: Create directories
        run: |
          New-Item -Path input -ItemType Directory -Force
          New-Item -Path output -ItemType Directory -Force
          New-Item -Path tools -ItemType Directory -Force

      - name: Download latest Slack Windows Installer (EXE)
        shell: pwsh
        run: |
          $downloadUrl = "https://downloads.slack-edge.com/releases_x64/SlackSetup.exe"
          Write-Host "Downloading Slack from: $downloadUrl"
          Invoke-WebRequest -Uri $downloadUrl -OutFile "input\SlackSetup.exe" -UserAgent "Mozilla/5.0" -ErrorAction Stop
          Write-Host "Downloaded SlackSetup.exe to input\"

      - name: Download Microsoft Win32 Content Prep Tool
        shell: pwsh
        run: |
          Write-Host "Downloading Microsoft Win32 Content Prep Tool..."
          Invoke-WebRequest -Uri "https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/releases/latest/download/IntuneWinAppUtil.exe" -OutFile "tools\IntuneWinAppUtil.exe" -ErrorAction Stop
          Write-Host "IntuneWinAppUtil.exe downloaded."

      - name: Get Slack Installer Version
        shell: pwsh
        run: |
          $version = (Get-Item "input\SlackSetup.exe").VersionInfo.FileVersion
          echo "SLACK_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Host "Slack Installer Version: $version"

      - name: Package Slack Installer into .intunewin
        shell: pwsh
        run: |
          & "tools\IntuneWinAppUtil.exe" -c "input" -s "SlackSetup.exe" -o "output" -q
          $sourceFileBaseName = [System.IO.Path]::GetFileNameWithoutExtension("SlackSetup.exe")
          $originalIntuneWinFile = Join-Path "output" "$sourceFileBaseName.intunewin"
          if (Test-Path $originalIntuneWinFile) {
            $newName = "Slack-Windows-$env:SLACK_VERSION.intunewin"
            Move-Item -Path $originalIntuneWinFile -Destination (Join-Path "output" $newName) -Force
            Write-Host "Renamed '$originalIntuneWinFile' to '$newName'"
          } else {
            Write-Error "Failed to find the generated .intunewin file after packaging."
            exit 1
          }

      - name: Upload Slack .intunewin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: slack-windows-intunewin
          path: output/*.intunewin
          retention-days: 7

  telegram:
    runs-on: windows-latest
    steps:
      - name: Create directories
        run: |
          New-Item -Path input -ItemType Directory -Force
          New-Item -Path output -ItemType Directory -Force
          New-Item -Path tools -ItemType Directory -Force

      - name: Download latest Telegram Windows Installer (EXE)
        shell: pwsh
        run: |
          $downloadUrl = "https://telegram.org/dl/desktop/win"
          Write-Host "Downloading Telegram from: $downloadUrl"
          Invoke-WebRequest -Uri $downloadUrl -OutFile "input\TelegramSetup.exe" -UserAgent "Mozilla/5.0" -ErrorAction Stop
          Write-Host "Downloaded TelegramSetup.exe to input\"

      - name: Download Microsoft Win32 Content Prep Tool
        shell: pwsh
        run: |
          Write-Host "Downloading Microsoft Win32 Content Prep Tool..."
          Invoke-WebRequest -Uri "https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/releases/latest/download/IntuneWinAppUtil.exe" -OutFile "tools\IntuneWinAppUtil.exe" -ErrorAction Stop
          Write-Host "IntuneWinAppUtil.exe downloaded."

      - name: Get Telegram Installer Version
        shell: pwsh
        run: |
          $version = (Get-Item "input\TelegramSetup.exe").VersionInfo.FileVersion
          echo "TELEGRAM_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Host "Telegram Installer Version: $version"

      - name: Package Telegram Installer into .intunewin
        shell: pwsh
        run: |
          & "tools\IntuneWinAppUtil.exe" -c "input" -s "TelegramSetup.exe" -o "output" -q
          $sourceFileBaseName = [System.IO.Path]::GetFileNameWithoutExtension("TelegramSetup.exe")
          $originalIntuneWinFile = Join-Path "output" "$sourceFileBaseName.intunewin"
          if (Test-Path $originalIntuneWinFile) {
            $newName = "Telegram-Windows-$env:TELEGRAM_VERSION.intunewin"
            Move-Item -Path $originalIntuneWinFile -Destination (Join-Path "output" $newName) -Force
            Write-Host "Renamed '$originalIntuneWinFile' to '$newName'"
          } else {
            Write-Error "Failed to find the generated .intunewin file after packaging."
            exit 1
          }

      - name: Upload Telegram .intunewin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: telegram-windows-intunewin
          path: output/*.intunewin
          retention-days: 7
