name: Build VSCode & Homebrew .intunemac Packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download and install AutoPkg
        run: |
          curl -L -o autopkg.pkg https://github.com/autopkg/autopkg/releases/latest/download/AutoPkg-2.7.5.pkg
          sudo installer -pkg autopkg.pkg -target /
          autopkg --version

      - name: Add AutoPkg recipe repos
        run: |
          autopkg repo-add https://github.com/autopkg/recipes.git
          autopkg repo-add https://github.com/autopkg/gerardkok-recipes.git
          if [ -d "./recipes" ]; then
            autopkg repo-add ./recipes
          fi

      - name: Set environment variable for custom processors
        run: echo "AUTO_PKG_PROCESSOR_PATHS=$(pwd)/processors" >> $GITHUB_ENV

      - name: Run VSCode .intunemac recipe
        run: autopkg run VSCode.intunemac.recipe --verbose

      - name: Run Homebrew .intunemac recipe
        run: autopkg run Homebrew.intunemac.recipe --verbose

      - name: Find and upload VSCode .intunemac artifact
        id: find-vscode
        run: |
          RECIPE_CACHE_DIR=$(autopkg pref-read CacheDir)
          VSCODE_FILE=$(find "$RECIPE_CACHE_DIR" -name "VSCode*.intunemac" | head -n 1)
          if [ -z "$VSCODE_FILE" ]; then
            echo "No VSCode .intunemac file found!"
            exit 1
          fi
          echo "VSCODE_FILE=$VSCODE_FILE" >> $GITHUB_ENV

      - name: Upload VSCode artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-intunemac
          path: ${{ env.VSCODE_FILE }}
          retention-days: 7

      - name: Find and upload Homebrew .intunemac artifact
        id: find-homebrew
        run: |
          RECIPE_CACHE_DIR=$(autopkg pref-read CacheDir)
          HOMEBREW_FILE=$(find "$RECIPE_CACHE_DIR" -name "Homebrew*.intunemac" | head -n 1)
          if [ -z "$HOMEBREW_FILE" ]; then
            echo "No Homebrew .intunemac file found!"
            exit 1
          fi
          echo "HOMEBREW_FILE=$HOMEBREW_FILE" >> $GITHUB_ENV

      - name: Upload Homebrew artifact
        uses: actions/upload-artifact@v4
        with:
          name: homebrew-intunemac
          path: ${{ env.HOMEBREW_FILE }}
          retention-days: 7
