name: Build VSCode .intunemac Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download and install AutoPkg (latest)
        run: |
          PKG_URL=$(curl -s https://api.github.com/repos/autopkg/autopkg/releases/latest \
            | grep browser_download_url \
            | grep '\.pkg' \
            | cut -d '"' -f 4)
          echo "Downloading AutoPkg from $PKG_URL"
          curl -L -o autopkg.pkg "$PKG_URL"
          sudo installer -pkg autopkg.pkg -target /
          autopkg --version

      - name: Add AutoPkg recipe repos
        run: |
          autopkg repo-add https://github.com/autopkg/recipes.git
          autopkg repo-add ./recipes

      - name: Set environment variable for custom processors
        run: echo "AUTO_PKG_PROCESSOR_PATHS=$(pwd)/processors" >> $GITHUB_ENV

      - name: Run VSCode.intunemac.recipe
        run: autopkg run VSCode.intunemac.recipe --verbose

      - name: Find and upload .intunemac artifact
        id: find-artifact
        run: |
          RECIPE_CACHE_DIR=$(autopkg pref-read CacheDir)
          echo "RECIPE_CACHE_DIR=$RECIPE_CACHE_DIR"
          INTUNEMAC_FILE=$(find "$RECIPE_CACHE_DIR" -name "*.intunemac" | head -n 1)
          if [ -z "$INTUNEMAC_FILE" ]; then
            echo "No .intunemac file found!"
            exit 1
          fi
          echo "INTUNEMAC_FILE=$INTUNEMAC_FILE" >> $GITHUB_ENV

      - name: Upload .intunemac artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-intunemac
          path: ${{ env.INTUNEMAC_FILE }}
          retention-days: 7
