name: Package Slack Windows IntuneWin

on:
  workflow_dispatch:

jobs:
  slack:
    runs-on: windows-latest
    steps:
      - name: Create directories
        run: |
          New-Item -Path input -ItemType Directory -Force
          New-Item -Path output -ItemType Directory -Force
          New-Item -Path tools -ItemType Directory -Force

      - name: Download latest Slack Windows Installer (EXE)
        run: |
          curl -L "https://slack.com/ssb/download-win" -o "input\SlackSetup.exe"
          echo "Downloaded SlackSetup.exe to input\"

      - name: Download IntuneWinAppUtil.exe
        run: |
          curl -L "https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/releases/latest/download/IntuneWinAppUtil.exe" -o "tools\IntuneWinAppUtil.exe"
          echo "Downloaded IntuneWinAppUtil.exe to tools\"

      - name: Get Slack Installer Version
        shell: pwsh
        run: |
          $version = (Get-Item "input\SlackSetup.exe").VersionInfo.FileVersion
          echo "SLACK_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "Slack Installer Version: $version"

      - name: Wrap Slack Installer into .intunewin
        shell: pwsh
        run: |
          & "tools\IntuneWinAppUtil.exe" -c "input" -s "SlackSetup.exe" -o "output" -q
          
          $intunewinPath = Get-ChildItem -Path "output" -Filter "*.intunewin" | Select-Object -ExpandProperty FullName
          if ($intunewinPath) {
            $newName = "Slack-Windows-$env:SLACK_VERSION.intunewin"
            Move-Item -Path $intunewinPath -Destination (Join-Path "output" $newName)
            echo "Renamed .intunewin to: $newName"
          } else {
            Write-Error "Failed to find the generated .intunewin file."
            exit 1
          }

      - name: Upload .intunewin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: slack-windows-intunewin
          path: output/*.intunewin
          retention-days: 7
