name: Build Slack & Telegram .intunewin for Intune

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Slack installer
        run: |
          Invoke-WebRequest -Uri "https://downloads.slack-edge.com/releases_x64/SlackSetup.exe" -OutFile "SlackSetup.exe"

      - name: Download Telegram installer
        run: |
          Invoke-WebRequest -Uri "https://telegram.org/dl/desktop/win64" -OutFile "TelegramSetup.exe"

      - name: Download Microsoft Win32 Content Prep Tool
        run: |
          Invoke-WebRequest -Uri "https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/releases/latest/download/IntuneWinAppUtil.exe" -OutFile "IntuneWinAppUtil.exe"

      - name: Wrap Slack installer
        run: |
          .\IntuneWinAppUtil.exe -c . -s SlackSetup.exe -o . -q

      - name: Wrap Telegram installer
        run: |
          .\IntuneWinAppUtil.exe -c . -s TelegramSetup.exe -o . -q

      - name: Upload .intunewin artifacts
        uses: actions/upload-artifact@v4
        with:
          name: slack-telegram-intunewin
          path: |
            *.intunewin
          retention-days: 7
